<?xml version="1.0" encoding="utf-8"?><Database Name="ShopQuanAo" Class="fsShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-C9Q9BBCB;Initial Catalog=ShopQuanAo;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ShopQuanAoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BaiDang" Member="BaiDangs">
    <Type Name="BaiDang">
      <Column Name="MaBaiViet" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDanhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TieuDeWeb" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NguoiTao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="BaiDang_DangHinhAnh" Member="DangHinhAnhs" ThisKey="MaBaiViet" OtherKey="MaBaiViet" Type="DangHinhAnh" />
      <Association Name="DanhMuc_BaiDang" Member="DanhMuc" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="DanhMuc" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="NguoiDung_BaiDang" Member="NguoiDung" ThisKey="NguoiTao" OtherKey="MaNguoiDung" Type="NguoiDung" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="MaChiTietDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DonHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangHinhAnh" Member="DangHinhAnhs">
    <Type Name="DangHinhAnh">
      <Column Name="MaHinhAnh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaBaiViet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="BaiDang_DangHinhAnh" Member="BaiDang" ThisKey="MaBaiViet" OtherKey="MaBaiViet" Type="BaiDang" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="MaDanhMuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DanhMuc_BaiDang" Member="BaiDangs" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="BaiDang" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangDatHang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangThanhToan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="ChiTietDonHang" />
      <Association Name="NguoiDung_DonHang" Member="NguoiDung" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaTriThuocTinh" Member="GiaTriThuocTinhs">
    <Type Name="GiaTriThuocTinh">
      <Column Name="MaGiaTriThuocTinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaThuocTinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="GiaTriThuocTinh_ThuocTinhSanPham" Member="ThuocTinhSanPhams" ThisKey="MaGiaTriThuocTinh" OtherKey="MaGiaTriThuocTinh" Type="ThuocTinhSanPham" />
      <Association Name="ThuocTinh_GiaTriThuocTinh" Member="ThuocTinh" ThisKey="MaThuocTinh" OtherKey="MaThuocTinh" Type="ThuocTinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VaiTro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NguoiDung_BaiDang" Member="BaiDangs" ThisKey="MaNguoiDung" OtherKey="NguoiTao" Type="BaiDang" />
      <Association Name="NguoiDung_DonHang" Member="DonHangs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="DonHang" />
      <Association Name="VaiTro_NguoiDung" Member="VaiTro1" ThisKey="VaiTro" OtherKey="MaVaiTro" Type="VaiTro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HinhAnhSanPham" Member="HinhAnhSanPhams">
    <Type Name="HinhAnhSanPham">
      <Column Name="MaAnhSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSanPhan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="SanPham_HinhAnhSanPham" Member="SanPham" ThisKey="MaSanPhan" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanHang" Member="NhanHangs">
    <Type Name="NhanHang">
      <Column Name="MaNhanHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="KhuVuc" Type="System.Data.Linq.Binary" DbType="VarBinary(30)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="NhanHang_SanPham" Member="SanPhams" ThisKey="MaNhanHang" OtherKey="MaNhanHang" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.Quyen" Member="Quyens">
    <Type Name="Quyen">
      <Column Name="MaQuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Quyen" Member="Quyen1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Quyen_VaiTroChoPhep" Member="VaiTroChoPheps" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="VaiTroChoPhep" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaTheLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhanHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="VideoSanPham" Type="System.String" DbType="NVarChar(158)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SanPham_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="ChiTietDonHang" />
      <Association Name="SanPham_HinhAnhSanPham" Member="HinhAnhSanPhams" ThisKey="MaSanPham" OtherKey="MaSanPhan" Type="HinhAnhSanPham" />
      <Association Name="SanPham_ThuocTinhSanPham" Member="ThuocTinhSanPhams" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="ThuocTinhSanPham" />
      <Association Name="NhanHang_SanPham" Member="NhanHang" ThisKey="MaNhanHang" OtherKey="MaNhanHang" Type="NhanHang" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="TheLoai_SanPham" Member="TheLoai" ThisKey="MaTheLoai" OtherKey="MaLoai" Type="TheLoai" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.ThuocTinh" Member="ThuocTinhs">
    <Type Name="ThuocTinh">
      <Column Name="MaThuocTinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ThuocTinh_GiaTriThuocTinh" Member="GiaTriThuocTinhs" ThisKey="MaThuocTinh" OtherKey="MaThuocTinh" Type="GiaTriThuocTinh" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoai" Member="TheLoais">
    <Type Name="TheLoai">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TheLoai_SanPham" Member="SanPhams" ThisKey="MaLoai" OtherKey="MaTheLoai" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.ThuocTinhSanPham" Member="ThuocTinhSanPhams">
    <Type Name="ThuocTinhSanPham">
      <Column Name="MaThuocTinhSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaGiaTriThuocTinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GiaTriThuocTinh_ThuocTinhSanPham" Member="GiaTriThuocTinh" ThisKey="MaGiaTriThuocTinh" OtherKey="MaGiaTriThuocTinh" Type="GiaTriThuocTinh" IsForeignKey="true" />
      <Association Name="SanPham_ThuocTinhSanPham" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VaiTro" Member="VaiTros">
    <Type Name="VaiTro">
      <Column Name="MaVaiTro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenVaiTro" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="VaiTro_NguoiDung" Member="NguoiDungs" ThisKey="MaVaiTro" OtherKey="VaiTro" Type="NguoiDung" />
      <Association Name="VaiTro_VaiTroChoPhep" Member="VaiTroChoPheps" ThisKey="MaVaiTro" OtherKey="MaVaiTro" Type="VaiTroChoPhep" />
    </Type>
  </Table>
  <Table Name="dbo.VaiTroChoPhep" Member="VaiTroChoPheps">
    <Type Name="VaiTroChoPhep">
      <Column Name="MaVaiTroQuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaVaiTro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaQuyen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Quyen_VaiTroChoPhep" Member="Quyen" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="Quyen" IsForeignKey="true" />
      <Association Name="VaiTro_VaiTroChoPhep" Member="VaiTro" ThisKey="MaVaiTro" OtherKey="MaVaiTro" Type="VaiTro" IsForeignKey="true" />
    </Type>
  </Table>
</Database>